name: geocoder
description: Forward and reverse geocoding.
version: 0.3.0
homepage: https://github.com/thginkwehttam/flutter_geocoder

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=2.2.1"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.aloisdeniel.geocoder
    pluginClass: GeocoderPlugin
